server.port=8081
spring.application.name=auth-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3360/pfedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pfeuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
